# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ebec0571796c904ecbb458843f277d6f9c7e8f714033d218c3a1a87dd220b16add7756276252597a16717223e88d175a3eea9949cb78f371b9b2be1cc788dab
  client_host: 'http://localhost:4200'

test:
  secret_key_base: df45fede1a1a72ce205918ef30ed8ae8a83b6fa2f9b9ffeed8a855a1d22159c8c303761a1fd36646d4f91cc7b53da776df403204bbc8e73cf4ed206aa924bd9a
  client_host: 'http://localhost:4200'


staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  client_host: <%= ENV["CLIENT_HOST"] %>


production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  client_host: <%= ENV["CLIENT_HOST"] %>
